#!/bin/sh

# https://rust-lang.github.io/rustup/cross-compilation.html
# https://doc.rust-lang.org/nightly/rustc/platform-support.html

rustup target add x86_64-unknown-linux-gnu
rustup target add x86_64-apple-darwin
rustup target add x86_64-pc-windows-gnu