#!/bin/bash

set -e

PWD=`pwd`
echo ${PWD}

mkdir -p ${PWD}/builder-assets
cd builder-assets

# From time to time the download link gets taken down and needs to be replaced with a new one.
# Here's where the current download link was found:
#  https://packages.debian.org/buster/amd64/libssl-dev/download
curl -O http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl-dev_1.1.1d-0+deb10u7_amd64.deb
ar p libssl-dev_1.1.1d-0+deb10u7_amd64.deb data.tar.xz | tar xvf -
rm -rf libssl-dev_1.1.1d-0+deb10u7_amd64.deb